#GitHub Actions名
name: CI/CD

#実行タイミング
on:
  push:
    branches: ['main']

#job定義
jobs:
  #job名定義（並列実行）
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Test Backend
        working-directory: back
        env:
          DATABASE_URL: postgresql://postgres:password@localhost:5432/app
          JWT_SECRET: secret
          GOOGLE_CLIENT_ID: dummy
          GOOGLE_CLIENT_SECRET: dummy
          GOOGLE_CALLBACK_URL: dummy
          GITHUB_CLIENT_ID: dummy
          GITHUB_CLIENT_SECRET: dummy
          GITHUB_CALLBACK_URL: dummy
        run: |
          npm install
          npm run test
          npm run test:e2e

  deploy:
    needs: test #先行JOBの正常終了後に実行
    runs-on: ubuntu-latest #job実行するOS(ランナー)

    steps:
      #リポジトリをこの環境に取り込み
      - name: Checkout repository #step名
        uses: actions/checkout@v4 #外部のAction

      - name: GitHub Secretsから秘密鍵をインストール
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: サーバー処理
        run: |
          #SSH接続
          ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }} << 'EOF'

          cd ~/TubeNote
          git reset --hard HEAD
          git pull

          #フロントのビルド
          cd ~/TubeNote/front
          npm install
          npm run build
          pm2 restart tubenote-front

          #バックのビルド
          cd ~/TubeNote/back
          npm install
          npx prisma migrate deploy
          npm run build
          pm2 restart tubenote-api

          EOF
